# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    globe_api:
        class: AppBundle\Services\GlobeApi
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


